// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc2
// source: proto/ghwebhook/v1/ghwebhook.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegistrationService_Register_FullMethodName   = "/ghwebhook.v1.RegistrationService/Register"
	RegistrationService_Unregister_FullMethodName = "/ghwebhook.v1.RegistrationService/Unregister"
)

// RegistrationServiceClient is the client API for RegistrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RegistrationService handles service check-ins.
type RegistrationServiceClient interface {
	// Register a service for a specific repository.
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// Unregister a service for a specific repository.
	Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type registrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationServiceClient(cc grpc.ClientConnInterface) RegistrationServiceClient {
	return &registrationServiceClient{cc}
}

func (c *registrationServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, RegistrationService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationServiceClient) Unregister(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, RegistrationService_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServiceServer is the server API for RegistrationService service.
// All implementations must embed UnimplementedRegistrationServiceServer
// for forward compatibility.
//
// RegistrationService handles service check-ins.
type RegistrationServiceServer interface {
	// Register a service for a specific repository.
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	// Unregister a service for a specific repository.
	Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedRegistrationServiceServer()
}

// UnimplementedRegistrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServiceServer struct{}

func (UnimplementedRegistrationServiceServer) Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedRegistrationServiceServer) Unregister(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedRegistrationServiceServer) mustEmbedUnimplementedRegistrationServiceServer() {}
func (UnimplementedRegistrationServiceServer) testEmbeddedByValue()                             {}

// UnsafeRegistrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServiceServer will
// result in compilation errors.
type UnsafeRegistrationServiceServer interface {
	mustEmbedUnimplementedRegistrationServiceServer()
}

func RegisterRegistrationServiceServer(s grpc.ServiceRegistrar, srv RegistrationServiceServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegistrationService_ServiceDesc, srv)
}

func _RegistrationService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegistrationService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegistrationService_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServiceServer).Unregister(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegistrationService_ServiceDesc is the grpc.ServiceDesc for RegistrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegistrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghwebhook.v1.RegistrationService",
	HandlerType: (*RegistrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegistrationService_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _RegistrationService_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ghwebhook/v1/ghwebhook.proto",
}

const (
	WebhookHandler_ReceiveWebhook_FullMethodName = "/ghwebhook.v1.WebhookHandler/ReceiveWebhook"
)

// WebhookHandlerClient is the client API for WebhookHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebhookHandler is the service implemented by clients to receive webhooks.
type WebhookHandlerClient interface {
	// ReceiveWebhook is called by the proxy when a webhook is received.
	ReceiveWebhook(ctx context.Context, in *WebhookEvent, opts ...grpc.CallOption) (*WebhookResponse, error)
}

type webhookHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookHandlerClient(cc grpc.ClientConnInterface) WebhookHandlerClient {
	return &webhookHandlerClient{cc}
}

func (c *webhookHandlerClient) ReceiveWebhook(ctx context.Context, in *WebhookEvent, opts ...grpc.CallOption) (*WebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebhookResponse)
	err := c.cc.Invoke(ctx, WebhookHandler_ReceiveWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookHandlerServer is the server API for WebhookHandler service.
// All implementations must embed UnimplementedWebhookHandlerServer
// for forward compatibility.
//
// WebhookHandler is the service implemented by clients to receive webhooks.
type WebhookHandlerServer interface {
	// ReceiveWebhook is called by the proxy when a webhook is received.
	ReceiveWebhook(context.Context, *WebhookEvent) (*WebhookResponse, error)
	mustEmbedUnimplementedWebhookHandlerServer()
}

// UnimplementedWebhookHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookHandlerServer struct{}

func (UnimplementedWebhookHandlerServer) ReceiveWebhook(context.Context, *WebhookEvent) (*WebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveWebhook not implemented")
}
func (UnimplementedWebhookHandlerServer) mustEmbedUnimplementedWebhookHandlerServer() {}
func (UnimplementedWebhookHandlerServer) testEmbeddedByValue()                        {}

// UnsafeWebhookHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookHandlerServer will
// result in compilation errors.
type UnsafeWebhookHandlerServer interface {
	mustEmbedUnimplementedWebhookHandlerServer()
}

func RegisterWebhookHandlerServer(s grpc.ServiceRegistrar, srv WebhookHandlerServer) {
	// If the following call panics, it indicates UnimplementedWebhookHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookHandler_ServiceDesc, srv)
}

func _WebhookHandler_ReceiveWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebhookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookHandlerServer).ReceiveWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookHandler_ReceiveWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookHandlerServer).ReceiveWebhook(ctx, req.(*WebhookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookHandler_ServiceDesc is the grpc.ServiceDesc for WebhookHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ghwebhook.v1.WebhookHandler",
	HandlerType: (*WebhookHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveWebhook",
			Handler:    _WebhookHandler_ReceiveWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ghwebhook/v1/ghwebhook.proto",
}
