// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: proto/ghwebhook/v1/ghwebhook.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepoFullName   string                 `protobuf:"bytes,1,opt,name=repo_full_name,json=repoFullName,proto3" json:"repo_full_name,omitempty"`     // e.g., "owner/repo"
	ServiceAddress string                 `protobuf:"bytes,2,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // e.g., "service.namespace.svc:50051"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetRepoFullName() string {
	if x != nil {
		return x.RepoFullName
	}
	return ""
}

func (x *RegistrationRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookResponse) Reset() {
	*x = WebhookResponse{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookResponse) ProtoMessage() {}

func (x *WebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookResponse.ProtoReflect.Descriptor instead.
func (*WebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{2}
}

func (x *WebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WebhookEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *EventHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebhookEvent_PullRequest
	//	*WebhookEvent_Issue
	Payload       isWebhookEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{3}
}

func (x *WebhookEvent) GetHeader() *EventHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WebhookEvent) GetPayload() isWebhookEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookEvent) GetPullRequest() *PullRequestEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebhookEvent_PullRequest); ok {
			return x.PullRequest
		}
	}
	return nil
}

func (x *WebhookEvent) GetIssue() *IssueEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebhookEvent_Issue); ok {
			return x.Issue
		}
	}
	return nil
}

type isWebhookEvent_Payload interface {
	isWebhookEvent_Payload()
}

type WebhookEvent_PullRequest struct {
	PullRequest *PullRequestEvent `protobuf:"bytes,2,opt,name=pull_request,json=pullRequest,proto3,oneof"`
}

type WebhookEvent_Issue struct {
	Issue *IssueEvent `protobuf:"bytes,3,opt,name=issue,proto3,oneof"`
}

func (*WebhookEvent_PullRequest) isWebhookEvent_Payload() {}

func (*WebhookEvent_Issue) isWebhookEvent_Payload() {}

type EventHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`             // e.g., "pull_request"
	ReceivedAtMs  int64                  `protobuf:"varint,2,opt,name=received_at_ms,json=receivedAtMs,proto3" json:"received_at_ms,omitempty"` // Proxy timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventHeader) Reset() {
	*x = EventHeader{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHeader) ProtoMessage() {}

func (x *EventHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHeader.ProtoReflect.Descriptor instead.
func (*EventHeader) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{4}
}

func (x *EventHeader) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventHeader) GetReceivedAtMs() int64 {
	if x != nil {
		return x.ReceivedAtMs
	}
	return 0
}

type PullRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	User          *User                  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Repository    *Repository            `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequestEvent) Reset() {
	*x = PullRequestEvent{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequestEvent) ProtoMessage() {}

func (x *PullRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequestEvent.ProtoReflect.Descriptor instead.
func (*PullRequestEvent) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{5}
}

func (x *PullRequestEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PullRequestEvent) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequestEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequestEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PullRequestEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PullRequestEvent) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type IssueEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	User          *User                  `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Repository    *Repository            `protobuf:"bytes,6,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueEvent) Reset() {
	*x = IssueEvent{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueEvent) ProtoMessage() {}

func (x *IssueEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueEvent.ProtoReflect.Descriptor instead.
func (*IssueEvent) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{6}
}

func (x *IssueEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *IssueEvent) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *IssueEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IssueEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *IssueEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *IssueEvent) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{7}
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP(), []int{8}
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_proto_ghwebhook_v1_ghwebhook_proto protoreflect.FileDescriptor

const file_proto_ghwebhook_v1_ghwebhook_proto_rawDesc = "" +
	"\n" +
	"\"proto/ghwebhook/v1/ghwebhook.proto\x12\fghwebhook.v1\"d\n" +
	"\x13RegistrationRequest\x12$\n" +
	"\x0erepo_full_name\x18\x01 \x01(\tR\frepoFullName\x12'\n" +
	"\x0fservice_address\x18\x02 \x01(\tR\x0eserviceAddress\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x0fWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc3\x01\n" +
	"\fWebhookEvent\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.ghwebhook.v1.EventHeaderR\x06header\x12C\n" +
	"\fpull_request\x18\x02 \x01(\v2\x1e.ghwebhook.v1.PullRequestEventH\x00R\vpullRequest\x120\n" +
	"\x05issue\x18\x03 \x01(\v2\x18.ghwebhook.v1.IssueEventH\x00R\x05issueB\t\n" +
	"\apayload\"R\n" +
	"\vEventHeader\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12$\n" +
	"\x0ereceived_at_ms\x18\x02 \x01(\x03R\freceivedAtMs\"\xce\x01\n" +
	"\x10PullRequestEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12&\n" +
	"\x04user\x18\x05 \x01(\v2\x12.ghwebhook.v1.UserR\x04user\x128\n" +
	"\n" +
	"repository\x18\x06 \x01(\v2\x18.ghwebhook.v1.RepositoryR\n" +
	"repository\"\xc8\x01\n" +
	"\n" +
	"IssueEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12&\n" +
	"\x04user\x18\x05 \x01(\v2\x12.ghwebhook.v1.UserR\x04user\x128\n" +
	"\n" +
	"repository\x18\x06 \x01(\v2\x18.ghwebhook.v1.RepositoryR\n" +
	"repository\"\x1c\n" +
	"\x04User\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\")\n" +
	"\n" +
	"Repository\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName2h\n" +
	"\x13RegistrationService\x12Q\n" +
	"\bRegister\x12!.ghwebhook.v1.RegistrationRequest\x1a\".ghwebhook.v1.RegistrationResponse2]\n" +
	"\x0eWebhookHandler\x12K\n" +
	"\x0eReceiveWebhook\x12\x1a.ghwebhook.v1.WebhookEvent\x1a\x1d.ghwebhook.v1.WebhookResponseB6Z4github.com/brotherlogic/ghwebhook/proto/ghwebhook/v1b\x06proto3"

var (
	file_proto_ghwebhook_v1_ghwebhook_proto_rawDescOnce sync.Once
	file_proto_ghwebhook_v1_ghwebhook_proto_rawDescData []byte
)

func file_proto_ghwebhook_v1_ghwebhook_proto_rawDescGZIP() []byte {
	file_proto_ghwebhook_v1_ghwebhook_proto_rawDescOnce.Do(func() {
		file_proto_ghwebhook_v1_ghwebhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ghwebhook_v1_ghwebhook_proto_rawDesc), len(file_proto_ghwebhook_v1_ghwebhook_proto_rawDesc)))
	})
	return file_proto_ghwebhook_v1_ghwebhook_proto_rawDescData
}

var file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ghwebhook_v1_ghwebhook_proto_goTypes = []any{
	(*RegistrationRequest)(nil),  // 0: ghwebhook.v1.RegistrationRequest
	(*RegistrationResponse)(nil), // 1: ghwebhook.v1.RegistrationResponse
	(*WebhookResponse)(nil),      // 2: ghwebhook.v1.WebhookResponse
	(*WebhookEvent)(nil),         // 3: ghwebhook.v1.WebhookEvent
	(*EventHeader)(nil),          // 4: ghwebhook.v1.EventHeader
	(*PullRequestEvent)(nil),     // 5: ghwebhook.v1.PullRequestEvent
	(*IssueEvent)(nil),           // 6: ghwebhook.v1.IssueEvent
	(*User)(nil),                 // 7: ghwebhook.v1.User
	(*Repository)(nil),           // 8: ghwebhook.v1.Repository
}
var file_proto_ghwebhook_v1_ghwebhook_proto_depIdxs = []int32{
	4, // 0: ghwebhook.v1.WebhookEvent.header:type_name -> ghwebhook.v1.EventHeader
	5, // 1: ghwebhook.v1.WebhookEvent.pull_request:type_name -> ghwebhook.v1.PullRequestEvent
	6, // 2: ghwebhook.v1.WebhookEvent.issue:type_name -> ghwebhook.v1.IssueEvent
	7, // 3: ghwebhook.v1.PullRequestEvent.user:type_name -> ghwebhook.v1.User
	8, // 4: ghwebhook.v1.PullRequestEvent.repository:type_name -> ghwebhook.v1.Repository
	7, // 5: ghwebhook.v1.IssueEvent.user:type_name -> ghwebhook.v1.User
	8, // 6: ghwebhook.v1.IssueEvent.repository:type_name -> ghwebhook.v1.Repository
	0, // 7: ghwebhook.v1.RegistrationService.Register:input_type -> ghwebhook.v1.RegistrationRequest
	3, // 8: ghwebhook.v1.WebhookHandler.ReceiveWebhook:input_type -> ghwebhook.v1.WebhookEvent
	1, // 9: ghwebhook.v1.RegistrationService.Register:output_type -> ghwebhook.v1.RegistrationResponse
	2, // 10: ghwebhook.v1.WebhookHandler.ReceiveWebhook:output_type -> ghwebhook.v1.WebhookResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_ghwebhook_v1_ghwebhook_proto_init() }
func file_proto_ghwebhook_v1_ghwebhook_proto_init() {
	if File_proto_ghwebhook_v1_ghwebhook_proto != nil {
		return
	}
	file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes[3].OneofWrappers = []any{
		(*WebhookEvent_PullRequest)(nil),
		(*WebhookEvent_Issue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ghwebhook_v1_ghwebhook_proto_rawDesc), len(file_proto_ghwebhook_v1_ghwebhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ghwebhook_v1_ghwebhook_proto_goTypes,
		DependencyIndexes: file_proto_ghwebhook_v1_ghwebhook_proto_depIdxs,
		MessageInfos:      file_proto_ghwebhook_v1_ghwebhook_proto_msgTypes,
	}.Build()
	File_proto_ghwebhook_v1_ghwebhook_proto = out.File
	file_proto_ghwebhook_v1_ghwebhook_proto_goTypes = nil
	file_proto_ghwebhook_v1_ghwebhook_proto_depIdxs = nil
}
